### PR TITLE
show colour in Images

### PR DESCRIPTION
**Pull request by way2muchnoise**
before:

after, still has a dark tune on it

### CODE REVIEW

**Comment by AfterLifeLochie** [comment]
This might be something being done in your rendering because the classic book rendering in the demo mod has no issues with gl_lighting or gl_light as far as I can see.

Can you please replicate this issue on the demo book to ensure it's not something being done by me?

**Comment by way2muchnoise** [comment]
@AfterLifeLochie Your image is black and white that is why it works for you.
This is what happens when I change the Resource to the image I use

**Comment by AfterLifeLochie** [comment]
Right -- in which case, the color problem is not just limited to gl_lighting. I'll do some digging.

**Comment by AfterLifeLochie** [comment]
This actually doesn't have anything to do with gl_lighting. It 's purely a problem with the glcolor property not being cleaned up (it's left at  0.0f, 0.0f, 0.0f, 1.0f after text).

**Pull request closed without merging**
